import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";
import prettier from "eslint-config-prettier/flat";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  prettier,
  {
    settings: {
      "import/resolver": { typescript: { project: "./tsconfig.json" } },
    },
    rules: {
      "import/order": [
        "error",
        {
          groups: ["builtin", "external", "internal"],
          pathGroups: [
            { pattern: "@/features/**", group: "internal", position: "before" },
            { pattern: "@/shared/**", group: "internal", position: "after" },
          ],
          distinctGroup: true,
          "newlines-between": "always",
          alphabetize: { order: "asc", caseInsensitive: true },
        },
      ],
    },
  },
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by `payload migrate:create`. Editing these by hand would
    // desync them from the database, so linting them serves no purpose.
    "src/shared/lib/payload/migrations/**",
    // Generated by Payload; rewritten on every scaffold regeneration.
    "src/app/(payload)/**",
  ]),
]);

export default eslintConfig;
