/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | "Pacific/Midway"
  | "Pacific/Niue"
  | "Pacific/Honolulu"
  | "Pacific/Rarotonga"
  | "America/Anchorage"
  | "Pacific/Gambier"
  | "America/Los_Angeles"
  | "America/Tijuana"
  | "America/Denver"
  | "America/Phoenix"
  | "America/Chicago"
  | "America/Guatemala"
  | "America/New_York"
  | "America/Bogota"
  | "America/Caracas"
  | "America/Santiago"
  | "America/Buenos_Aires"
  | "America/Sao_Paulo"
  | "Atlantic/South_Georgia"
  | "Atlantic/Azores"
  | "Atlantic/Cape_Verde"
  | "Europe/London"
  | "Europe/Berlin"
  | "Africa/Lagos"
  | "Europe/Athens"
  | "Africa/Cairo"
  | "Europe/Moscow"
  | "Asia/Riyadh"
  | "Asia/Dubai"
  | "Asia/Baku"
  | "Asia/Karachi"
  | "Asia/Tashkent"
  | "Asia/Calcutta"
  | "Asia/Dhaka"
  | "Asia/Almaty"
  | "Asia/Jakarta"
  | "Asia/Bangkok"
  | "Asia/Shanghai"
  | "Asia/Singapore"
  | "Asia/Tokyo"
  | "Asia/Seoul"
  | "Australia/Brisbane"
  | "Australia/Sydney"
  | "Pacific/Guam"
  | "Pacific/Noumea"
  | "Pacific/Auckland"
  | "Pacific/Fiji";

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    members: Member;
    events: Event;
    projects: Project;
    gallery: Gallery;
    applications: Application;
    posts: Post;
    exports: Export;
    imports: Import;
    "payload-kv": PayloadKv;
    "payload-jobs": PayloadJob;
    "payload-locked-documents": PayloadLockedDocument;
    "payload-preferences": PayloadPreference;
    "payload-migrations": PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    members: MembersSelect<false> | MembersSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    gallery: GallerySelect<false> | GallerySelect<true>;
    applications: ApplicationsSelect<false> | ApplicationsSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    exports: ExportsSelect<false> | ExportsSelect<true>;
    imports: ImportsSelect<false> | ImportsSelect<true>;
    "payload-kv": PayloadKvSelect<false> | PayloadKvSelect<true>;
    "payload-jobs": PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    "payload-locked-documents":
      PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    "payload-preferences":
      PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    "payload-migrations":
      PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: ("false" | "none" | "null") | false | null | "es" | "es"[];
  globals: {
    hero: Hero;
    manifesto: Manifesto;
    history: History;
    recruitment: Recruitment;
  };
  globalsSelect: {
    hero: HeroSelect<false> | HeroSelect<true>;
    manifesto: ManifestoSelect<false> | ManifestoSelect<true>;
    history: HistorySelect<false> | HistorySelect<true>;
    recruitment: RecruitmentSelect<false> | RecruitmentSelect<true>;
  };
  locale: "es";
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: {
      createCollectionExport: TaskCreateCollectionExport;
      createCollectionImport: TaskCreateCollectionImport;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role?: ("admin" | "editor" | "blogger" | "viewer") | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: "users";
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members".
 */
export interface Member {
  id: number;
  fullName: string;
  photo?: (number | null) | Media;
  major?:
    | (
        | "computacion"
        | "ciencia-de-datos-e-inteligencia-artificial"
        | "electricidad"
        | "electronica-y-automatizacion"
        | "telecomunicaciones"
        | "telematica"
        | "alimentos"
        | "ingenieria-industrial"
        | "materiales"
        | "mecanica"
        | "mecatronica"
        | "administracion-de-empresas"
        | "arqueologia"
        | "auditoria-y-control-de-gestion"
        | "economia"
        | "turismo"
        | "estadistica"
        | "ingenieria-quimica"
        | "logistica-y-transporte"
        | "matematica"
        | "biologia"
        | "ingenieria-agricola-y-biologica"
        | "geologia"
        | "ingenieria-civil"
        | "minas"
        | "petroleos"
        | "acuicultura"
        | "ingenieria-naval"
        | "oceanografia"
        | "animacion-digital-y-videojuegos"
        | "diseno-de-productos"
        | "diseno-grafico"
        | "produccion-para-medios-de-comunicacion"
      )
    | null;
  position?: string | null;
  status: "active" | "alumni";
  joinedAt?: string | null;
  githubUrl?: string | null;
  linkedinUrl?: string | null;
  order?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: number;
  title: string;
  slug: string;
  description: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ("ltr" | "rtl") | null;
      format: "left" | "start" | "center" | "right" | "end" | "justify" | "";
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  startsAt: string;
  endsAt?: string | null;
  location: string;
  cover: number | Media;
  registrationUrl?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  /**
   * Two or three lines. This is what the card shows.
   */
  summary: string;
  areas: (
    "web" | "mobile" | "machine-learning" | "data-science" | "iot" | "research"
  )[];
  status: "active" | "completed";
  /**
   * The large card at the top of the projects section. Only the most recent featured project is shown.
   */
  featured?: boolean | null;
  cover?: (number | null) | Media;
  year?: number | null;
  repositoryUrl?: string | null;
  externalUrl?: string | null;
  members?: (number | Member)[] | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Photos are published as albums. One album is one occasion, not one picture.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery".
 */
export interface Gallery {
  id: number;
  title: string;
  date: string;
  cover: number | Media;
  /**
   * Optional. Link the album to the occasion it came from; leave empty for a loose set.
   */
  event?: (number | null) | Event;
  images: {
    image: number | Media;
    caption?: string | null;
    id?: string | null;
  }[];
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "applications".
 */
export interface Application {
  id: number;
  fullName: string;
  email: string;
  major:
    | "computacion"
    | "ciencia-de-datos-e-inteligencia-artificial"
    | "electricidad"
    | "electronica-y-automatizacion"
    | "telecomunicaciones"
    | "telematica"
    | "alimentos"
    | "ingenieria-industrial"
    | "materiales"
    | "mecanica"
    | "mecatronica"
    | "administracion-de-empresas"
    | "arqueologia"
    | "auditoria-y-control-de-gestion"
    | "economia"
    | "turismo"
    | "estadistica"
    | "ingenieria-quimica"
    | "logistica-y-transporte"
    | "matematica"
    | "biologia"
    | "ingenieria-agricola-y-biologica"
    | "geologia"
    | "ingenieria-civil"
    | "minas"
    | "petroleos"
    | "acuicultura"
    | "ingenieria-naval"
    | "oceanografia"
    | "animacion-digital-y-videojuegos"
    | "diseno-de-productos"
    | "diseno-grafico"
    | "produccion-para-medios-de-comunicacion";
  interests: (
    "web" | "mobile" | "machine-learning" | "data-science" | "iot" | "research"
  )[];
  message?: string | null;
  status: "pending" | "accepted" | "rejected";
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: number;
  title: string;
  slug: string;
  excerpt: string;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ("ltr" | "rtl") | null;
      format: "left" | "start" | "center" | "right" | "end" | "justify" | "";
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  cover?: (number | null) | Media;
  category: "tutorial" | "anuncio" | "proyecto" | "evento";
  author: number | Member;
  publishedAt: string;
  /**
   * Worked out from the content. Editing it does nothing.
   */
  readingTime?: number | null;
  updatedAt: string;
  createdAt: string;
  _status?: ("draft" | "published") | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exports".
 */
export interface Export {
  id: number;
  name?: string | null;
  format: "csv" | "json";
  limit?: number | null;
  page?: number | null;
  sort?: string | null;
  sortOrder?: ("asc" | "desc") | null;
  locale?: ("all" | "es") | null;
  drafts?: ("yes" | "no") | null;
  selectionToUse?: ("currentSelection" | "currentFilters" | "all") | null;
  fields?: string[] | null;
  collectionSlug: string;
  where?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "imports".
 */
export interface Import {
  id: number;
  collectionSlug: string;
  importMode?: ("create" | "update" | "upsert") | null;
  matchField?: string | null;
  status?: ("pending" | "completed" | "partial" | "failed") | null;
  summary?: {
    imported?: number | null;
    updated?: number | null;
    total?: number | null;
    issues?: number | null;
    issueDetails?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: number;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug:
          "inline" | "createCollectionExport" | "createCollectionImport";
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: "failed" | "succeeded";
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?:
    ("inline" | "createCollectionExport" | "createCollectionImport") | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: "users";
        value: number | User;
      } | null)
    | ({
        relationTo: "media";
        value: number | Media;
      } | null)
    | ({
        relationTo: "members";
        value: number | Member;
      } | null)
    | ({
        relationTo: "events";
        value: number | Event;
      } | null)
    | ({
        relationTo: "projects";
        value: number | Project;
      } | null)
    | ({
        relationTo: "gallery";
        value: number | Gallery;
      } | null)
    | ({
        relationTo: "applications";
        value: number | Application;
      } | null)
    | ({
        relationTo: "posts";
        value: number | Post;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: "users";
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: "users";
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "members_select".
 */
export interface MembersSelect<T extends boolean = true> {
  fullName?: T;
  photo?: T;
  major?: T;
  position?: T;
  status?: T;
  joinedAt?: T;
  githubUrl?: T;
  linkedinUrl?: T;
  order?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  description?: T;
  startsAt?: T;
  endsAt?: T;
  location?: T;
  cover?: T;
  registrationUrl?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  summary?: T;
  areas?: T;
  status?: T;
  featured?: T;
  cover?: T;
  year?: T;
  repositoryUrl?: T;
  externalUrl?: T;
  members?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "gallery_select".
 */
export interface GallerySelect<T extends boolean = true> {
  title?: T;
  date?: T;
  cover?: T;
  event?: T;
  images?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "applications_select".
 */
export interface ApplicationsSelect<T extends boolean = true> {
  fullName?: T;
  email?: T;
  major?: T;
  interests?: T;
  message?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  cover?: T;
  category?: T;
  author?: T;
  publishedAt?: T;
  readingTime?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "exports_select".
 */
export interface ExportsSelect<T extends boolean = true> {
  name?: T;
  format?: T;
  limit?: T;
  page?: T;
  sort?: T;
  sortOrder?: T;
  locale?: T;
  drafts?: T;
  selectionToUse?: T;
  fields?: T;
  collectionSlug?: T;
  where?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "imports_select".
 */
export interface ImportsSelect<T extends boolean = true> {
  collectionSlug?: T;
  importMode?: T;
  matchField?: T;
  status?: T;
  summary?:
    | T
    | {
        imported?: T;
        updated?: T;
        total?: T;
        issues?: T;
        issueDetails?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero".
 */
export interface Hero {
  id: number;
  eyebrow: string;
  headline: string;
  description: string;
  primaryCta: {
    label: string;
    href: string;
  };
  secondaryCta: {
    label: string;
    href: string;
  };
  memberCountLabel: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "manifesto".
 */
export interface Manifesto {
  id: number;
  eyebrow: string;
  body: string;
  signature: string;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "history".
 */
export interface History {
  id: number;
  milestones: {
    year: string;
    title: string;
    description: string;
    id?: string | null;
  }[];
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * The dates the club accepts applications. Open and closed are worked out from these; there is no switch to flip.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recruitment".
 */
export interface Recruitment {
  id: number;
  opensAt?: string | null;
  closesAt?: string | null;
  /**
   * Shown in place of the form outside the window.
   */
  closedMessage?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "hero_select".
 */
export interface HeroSelect<T extends boolean = true> {
  eyebrow?: T;
  headline?: T;
  description?: T;
  primaryCta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  secondaryCta?:
    | T
    | {
        label?: T;
        href?: T;
      };
  memberCountLabel?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "manifesto_select".
 */
export interface ManifestoSelect<T extends boolean = true> {
  eyebrow?: T;
  body?: T;
  signature?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "history_select".
 */
export interface HistorySelect<T extends boolean = true> {
  milestones?:
    | T
    | {
        year?: T;
        title?: T;
        description?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "recruitment_select".
 */
export interface RecruitmentSelect<T extends boolean = true> {
  opensAt?: T;
  closesAt?: T;
  closedMessage?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: "full";
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskCreateCollectionExport".
 */
export interface TaskCreateCollectionExport {
  input: {
    id: string;
    name: string;
    batchSize?: number | null;
    collectionSlug:
      | "users"
      | "media"
      | "members"
      | "events"
      | "projects"
      | "gallery"
      | "applications"
      | "posts"
      | "exports"
      | "imports";
    drafts?: ("yes" | "no") | null;
    exportCollection: string;
    fields?: string[] | null;
    format: "csv" | "json";
    limit?: number | null;
    locale?: string | null;
    maxLimit?: number | null;
    page?: number | null;
    sort?: string | null;
    userCollection?: string | null;
    userID?: string | null;
    where?:
      | {
          [k: string]: unknown;
        }
      | unknown[]
      | string
      | number
      | boolean
      | null;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskCreateCollectionImport".
 */
export interface TaskCreateCollectionImport {
  input: {
    importId: string;
    importCollection: string;
    userID?: string | null;
    userCollection?: string | null;
    batchSize?: number | null;
    debug?: boolean | null;
    defaultVersionStatus?: ("draft" | "published") | null;
    maxLimit?: number | null;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}

declare module "payload" {
  export interface GeneratedTypes extends Config {}
}
